name: Scheduled Tests

on:
  workflow_dispatch:
  schedule:
    - cron: "0 17 * * 6"

jobs:
  test:
    uses: ./.github/workflows/pytest-workflow-call.yaml
  static-type-check:
    uses: ./.github/workflows/static-type-check-workflow-call.yaml
  code-style-check:
    uses: ./.github/workflows/code-style-check-workflow-call.yaml
